checks:
    javascript: true

build:
    dependencies:
        #before:
            #- npm install istanbul   # or add it as part of your package.json

    tests:
        override:
            -
                #command: 'istanbul cover --report clover test.js'
                command: 'cd react-frontend && npm test'
                coverage:
                    file: 'react-frontend/coverage/clover.xml'
                    format: 'clover'
