checks:
    javascript: true

build:
    environment:
        node: '9.2.0'

    tests:
        override:
            -
                #command: 'istanbul cover --report clover test.js'
                command: 'npm test'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
