version: "3"
services:
  node7:
    image: "node:7"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - DBWEBB_PORT=3000
    volumes:
      - ./:/home/node/app
    ports:
      - "1337:3000"
    command: "npm start"

  node8:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - DBWEBB_PORT=3000
    volumes:
      - ./:/home/node/app
    ports:
      - "1338:3000"
    command: "npm start"

  node9:
    image: "node:9"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - DBWEBB_PORT=3000
    volumes:
      - ./:/home/node/app
    ports:
      - "1339:3000"
    command: "npm start"
